/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package App.View;

import App.Dao.FilmDao;
import App.Dao.TicketDao;
import App.Helpers.MessageDialog;
import App.Model.Film;
import App.Model.Ticket_model;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * @author win10
 */
public class BuyTicketPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyTicket
     */
    public BuyTicketPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Buyticket = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Film = new javax.swing.JTable();

        jButton_Buyticket.setBackground(new java.awt.Color(255, 51, 51));
        jButton_Buyticket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Buyticket.setText("Đặt vé");
        jButton_Buyticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuyticketActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Danh sách lịch chiếu toàn bộ phim");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0))
        );

        jTable_Film.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_Film.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Avartar 2", "avt2"}
            },
            new String [] {
                "Tên Phim", "Mã Phim"
            }
        ));
        jScrollPane2.setViewportView(jTable_Film);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Buyticket, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Buyticket, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BuyticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuyticketActionPerformed
        Ticket TicketDialog = new Ticket(null, true);
        FilmDao filmDao = new FilmDao();
        TicketDao ticketDao = new TicketDao();
        int row = jTable_Film.getSelectedRow();
        if(row >= 0){
            try {
                Film film = filmDao.check(jTable_Film.getValueAt(row, 0).toString(), jTable_Film.getValueAt(row, 1).toString());
                ArrayList<Ticket_model> list = ticketDao.list(film.getIdFilm());
                TicketDialog.setList(list);
                TicketDialog.setColor();
            } catch (Exception ex) {
                Logger.getLogger(BuyTicketPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            MessageDialog.showMessageDialog(jPanel1, "Vui lòng chọn phim", "Thông báo");
            return ;
        }
        TicketDialog.setVisible(true);
    }//GEN-LAST:event_jButton_BuyticketActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Buyticket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Film;
    // End of variables declaration//GEN-END:variables
}
