/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App.View;

import App.Dao.FilmDao;
import App.Dao.TicketDao;
import App.Model.Ticket_model;
import App.Model.User;
import java.awt.GraphicsEnvironment;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author win10
 */
public class MainForm extends javax.swing.JFrame {
    
    private UserPanel userPanel;
    private BuyTicketPanel buyTicketPanel;
    private HistoryPanel historyPanel;
    private ShowTimesPanel showTimesPanel;
    private RevenuePanel revenuePanel;
    public User user;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //this.setSize(800, 700);
        this.setLocationRelativeTo(null);
        Login loginDialog = new Login(this, true);
        loginDialog.setVisible(true);
        this.user = loginDialog.getUser();
        processLoginSuccessful();
    }
    
    private void processLoginSuccessful() {
        if (this.user.getPosition().equals("Quản lí")) {
            jButton_User.setEnabled(true);
            jMenuItem_User.setEnabled(true);
            jButton_manager.setEnabled(true);
            jMenuItem_manager.setEnabled(true);
            jButton_History.setEnabled(false);
            jMenuItem_History.setEnabled(false);
            jButton_BuyTicket.setEnabled(false);
            jMenuItem_BuyTicket.setEnabled(false);
            jButton_revenue.setEnabled(true);
            jMenuItem_revenue.setEnabled(true);
        } else if (this.user.getPosition().equals("Khách hàng")) {
            jButton_User.setEnabled(true);
            jMenuItem_User.setEnabled(true);
            jButton_manager.setEnabled(false);
            jMenuItem_manager.setEnabled(false);
            jButton_History.setEnabled(true);
            jMenuItem_History.setEnabled(true);
            jButton_BuyTicket.setEnabled(true);
            jMenuItem_BuyTicket.setEnabled(true);
            jButton_revenue.setEnabled(false);
            jMenuItem_revenue.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton_Logout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton_User = new javax.swing.JButton();
        jButton_BuyTicket = new javax.swing.JButton();
        jButton_History = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton_manager = new javax.swing.JButton();
        jButton_revenue = new javax.swing.JButton();
        jTabbedPane_MainBoard = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_User = new javax.swing.JMenuItem();
        jMenuItem_History = new javax.swing.JMenuItem();
        jMenuItem_revenue = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Logout = new javax.swing.JMenuItem();
        jMenuItem_Exit = new javax.swing.JMenuItem();
        jMenu_Historty = new javax.swing.JMenu();
        jMenuItem_BuyTicket = new javax.swing.JMenuItem();
        jMenuItem_manager = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);

        jButton_Logout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Log-Out-icon-24.png"))); // NOI18N
        jButton_Logout.setText("Đăng Xuất");
        jButton_Logout.setFocusable(false);
        jButton_Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_Logout);
        jToolBar1.add(jSeparator1);

        jButton_User.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/brown-man-icon-24.png"))); // NOI18N
        jButton_User.setText("Tài Khoản");
        jButton_User.setFocusable(false);
        jButton_User.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_User.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UserActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_User);

        jButton_BuyTicket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_BuyTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ticket-icon-24.png"))); // NOI18N
        jButton_BuyTicket.setText("Mua vé");
        jButton_BuyTicket.setFocusable(false);
        jButton_BuyTicket.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_BuyTicket.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_BuyTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuyTicketActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_BuyTicket);

        jButton_History.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_History.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Alarm-clock-icon-24.png"))); // NOI18N
        jButton_History.setText("Lịch Sử");
        jButton_History.setFocusable(false);
        jButton_History.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_History.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HistoryActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_History);
        jToolBar1.add(jSeparator4);

        jButton_manager.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Business-Manager-icon_24.png"))); // NOI18N
        jButton_manager.setText("Quản Lí");
        jButton_manager.setFocusable(false);
        jButton_manager.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_manager.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_managerActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_manager);

        jButton_revenue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_revenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chart-icon_24.png"))); // NOI18N
        jButton_revenue.setText("Doanh Thu");
        jButton_revenue.setFocusable(false);
        jButton_revenue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_revenue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_revenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_revenueActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_revenue);

        jMenu1.setText("Cá Nhân");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem_User.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem_User.setText("Tài Khoản");
        jMenuItem_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_UserActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_User);

        jMenuItem_History.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_History.setText("Lịch Sử");
        jMenuItem_History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_HistoryActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_History);

        jMenuItem_revenue.setText("Doanh Thu");
        jMenuItem_revenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_revenueActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_revenue);
        jMenu1.add(jSeparator3);

        jMenuItem_Logout.setText("Đăng Xuất");
        jMenuItem_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Logout);

        jMenuItem_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem_Exit.setText("Thoát");
        jMenuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Exit);

        jMenuBar1.add(jMenu1);

        jMenu_Historty.setText("Chức Năng");
        jMenu_Historty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_HistortyActionPerformed(evt);
            }
        });

        jMenuItem_BuyTicket.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem_BuyTicket.setText("Mua vé");
        jMenuItem_BuyTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_BuyTicketActionPerformed(evt);
            }
        });
        jMenu_Historty.add(jMenuItem_BuyTicket);

        jMenuItem_manager.setText("Quản lí");
        jMenuItem_manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_managerActionPerformed(evt);
            }
        });
        jMenu_Historty.add(jMenuItem_manager);

        jMenuBar1.add(jMenu_Historty);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane_MainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane_MainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LogoutActionPerformed
        this.jTabbedPane_MainBoard.removeAll();
        Login login = new Login(this, true);
        login.setVisible(true);
        this.user = login.getUser();
        if (user == null) {
            jButton_User.setEnabled(false);
            jMenuItem_User.setEnabled(false);
            jButton_manager.setEnabled(false);
            jMenuItem_manager.setEnabled(false);
            jButton_History.setEnabled(false);
            jMenuItem_History.setEnabled(false);
            jButton_BuyTicket.setEnabled(false);
            jMenuItem_BuyTicket.setEnabled(false);
            jButton_revenue.setEnabled(false);
            jMenuItem_revenue.setEnabled(false);
        } else
            processLoginSuccessful();
    }//GEN-LAST:event_jMenuItem_LogoutActionPerformed

    private void jMenuItem_BuyTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_BuyTicketActionPerformed
        this.jTabbedPane_MainBoard.remove(userPanel);
        this.jTabbedPane_MainBoard.remove(historyPanel);
        this.jTabbedPane_MainBoard.remove(showTimesPanel);
        this.jTabbedPane_MainBoard.remove(revenuePanel);
        this.revenuePanel = null;
        this.userPanel = null;
        this.historyPanel = null;
        this.showTimesPanel = null;
        FilmDao dao = new FilmDao();
        if (buyTicketPanel == null) {
            buyTicketPanel = new BuyTicketPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/Image/shopping-icon_16.png"));
            buyTicketPanel.setUser(this.user);
            try {
                buyTicketPanel.setTable(dao.select());
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            jTabbedPane_MainBoard.addTab("Mua vé", icon, buyTicketPanel, "Mua vé");
        }
        jTabbedPane_MainBoard.setSelectedComponent(buyTicketPanel);
    }//GEN-LAST:event_jMenuItem_BuyTicketActionPerformed

    private void jMenuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ExitActionPerformed
        System.out.println("Tớ là hoàng cute nè hihi -_-");
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_ExitActionPerformed

    private void jButton_HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HistoryActionPerformed
        jMenuItem_HistoryActionPerformed(evt);
    }//GEN-LAST:event_jButton_HistoryActionPerformed

    private void jMenuItem_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_UserActionPerformed
        this.jTabbedPane_MainBoard.remove(buyTicketPanel);
        this.jTabbedPane_MainBoard.remove(historyPanel);
        this.jTabbedPane_MainBoard.remove(showTimesPanel);
        this.jTabbedPane_MainBoard.remove(revenuePanel);
        this.revenuePanel = null;
        this.buyTicketPanel = null;
        this.historyPanel = null;
        this.showTimesPanel = null;
        if (userPanel == null) {
            userPanel = new UserPanel();
            userPanel.setText(this.user);
            ImageIcon icon = new ImageIcon(getClass().getResource("/Image/user-info-icon_16.png"));
            jTabbedPane_MainBoard.addTab("Tài Khoản", icon, userPanel, "Tài Khoản");
        }
        jTabbedPane_MainBoard.setSelectedComponent(userPanel);
    }//GEN-LAST:event_jMenuItem_UserActionPerformed

    private void jButton_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UserActionPerformed
        jMenuItem_UserActionPerformed(evt);
    }//GEN-LAST:event_jButton_UserActionPerformed

    private void jMenu_HistortyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_HistortyActionPerformed

    }//GEN-LAST:event_jMenu_HistortyActionPerformed

    private void jMenuItem_HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_HistoryActionPerformed
        this.jTabbedPane_MainBoard.remove(buyTicketPanel);
        this.jTabbedPane_MainBoard.remove(userPanel);
        this.jTabbedPane_MainBoard.remove(showTimesPanel);
        this.jTabbedPane_MainBoard.remove(revenuePanel);
        this.revenuePanel = null;
        this.buyTicketPanel = null;
        this.userPanel = null;
        this.showTimesPanel = null;
        TicketDao dao = new TicketDao();
        if (historyPanel == null) {
            historyPanel = new HistoryPanel();
            try {
                ArrayList<Ticket_model> list = new ArrayList<>();
                list = dao.list1(user.getPhoneNumber());
                historyPanel.setList(list);
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon icon = new ImageIcon(getClass().getResource("/Image/Actions-view-history-icon_16.png"));
            jTabbedPane_MainBoard.addTab("Lịch sử", icon, historyPanel, "Lịch sử");
        }
        jTabbedPane_MainBoard.setSelectedComponent(historyPanel);
    }//GEN-LAST:event_jMenuItem_HistoryActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jButton_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogoutActionPerformed
        jMenuItem_LogoutActionPerformed(evt);
    }//GEN-LAST:event_jButton_LogoutActionPerformed

    private void jButton_BuyTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuyTicketActionPerformed
        jMenuItem_BuyTicketActionPerformed(evt);
    }//GEN-LAST:event_jButton_BuyTicketActionPerformed

    private void jButton_managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_managerActionPerformed
        this.jTabbedPane_MainBoard.remove(buyTicketPanel);
        this.jTabbedPane_MainBoard.remove(userPanel);
        this.jTabbedPane_MainBoard.remove(historyPanel);
        this.jTabbedPane_MainBoard.remove(revenuePanel);
        this.revenuePanel = null;
        this.historyPanel = null;
        this.userPanel = null;
        this.buyTicketPanel = null;
        FilmDao dao = new FilmDao();
        if (showTimesPanel == null) {
            showTimesPanel = new ShowTimesPanel();
            try {
                showTimesPanel.setTable(dao.select());
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon icon = new ImageIcon(getClass().getResource("/Image/Manager-icon_16.png"));
            jTabbedPane_MainBoard.addTab("Tài Khoản", icon, showTimesPanel, "Tài Khoản");
        }
        jTabbedPane_MainBoard.setSelectedComponent(showTimesPanel);
    }//GEN-LAST:event_jButton_managerActionPerformed

    private void jMenuItem_managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_managerActionPerformed
        jButton_managerActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem_managerActionPerformed

    private void jButton_revenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_revenueActionPerformed
        this.jTabbedPane_MainBoard.remove(buyTicketPanel);
        this.jTabbedPane_MainBoard.remove(userPanel);
        this.jTabbedPane_MainBoard.remove(historyPanel);
        this.jTabbedPane_MainBoard.remove(showTimesPanel);
        this.showTimesPanel = null;
        this.revenuePanel = null;
        this.historyPanel = null;
        this.userPanel = null;
        this.buyTicketPanel = null;
        if (revenuePanel == null) {
            try {
                revenuePanel = new RevenuePanel();
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon icon = new ImageIcon(getClass().getResource("/Image/chart-bar-chart-icon_16.png"));
            jTabbedPane_MainBoard.addTab("Tài Khoản", icon, revenuePanel, "Tài Khoản");
        }
        jTabbedPane_MainBoard.setSelectedComponent(revenuePanel);
    }//GEN-LAST:event_jButton_revenueActionPerformed

    private void jMenuItem_revenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_revenueActionPerformed
           jButton_revenueActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem_revenueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_BuyTicket;
    private javax.swing.JButton jButton_History;
    private javax.swing.JButton jButton_Logout;
    private javax.swing.JButton jButton_User;
    private javax.swing.JButton jButton_manager;
    private javax.swing.JButton jButton_revenue;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_BuyTicket;
    private javax.swing.JMenuItem jMenuItem_Exit;
    private javax.swing.JMenuItem jMenuItem_History;
    private javax.swing.JMenuItem jMenuItem_Logout;
    private javax.swing.JMenuItem jMenuItem_User;
    private javax.swing.JMenuItem jMenuItem_manager;
    private javax.swing.JMenuItem jMenuItem_revenue;
    private javax.swing.JMenu jMenu_Historty;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane_MainBoard;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
