/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package App.View;

import App.Dao.TicketDao;
import App.Helpers.MessageDialog;
import App.Model.Ticket_model;
import App.Model.User;
import java.awt.Button;
import java.awt.Color;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author win10
 */
public class Ticket extends javax.swing.JDialog {

    /**
     * Creates new form Ticket
     */
    private double s = 0;
    private User user;
    private ArrayList<Ticket_model> list = new ArrayList<>();
    Locale lc = new Locale("vn", "VN");
    NumberFormat ss = NumberFormat.getCurrencyInstance(lc);

    public Ticket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    public void setUser(User user) {
        this.user = user;
    }

    public void setList(ArrayList<Ticket_model> list) {
        this.list = list;
    }

    public void setYellow(JButton btn) {
        btn.setBackground(Color.YELLOW);
    }

    public void setWhite(JButton btn) {
        btn.setBackground(Color.WHITE);
    }

    public void setColor() {
        int i = 1;
        for (Ticket_model t : list) {
            if (i == 1) {
                if (t.isStatusTicket() == 1) {
                    jButton_A1.setBackground(Color.WHITE);
                } else if (t.isStatusTicket() == 3) {
                    jButton_A1.setBackground(Color.red);
                }
            } else if (i == 2) {
                if (t.isStatusTicket() == 1) {
                    jButton_A2.setBackground(Color.WHITE);
                } else if (t.isStatusTicket() == 3) {
                    jButton_A2.setBackground(Color.red);
                }
            } else if (i == 3) {
                if (t.isStatusTicket() == 1) {
                    jButton_A3.setBackground(Color.WHITE);
                } else if (t.isStatusTicket() == 3) {
                    jButton_A3.setBackground(Color.red);
                }
            } else if (i == 4) {
                if (t.isStatusTicket() == 1) {
                    jButton_B1.setBackground(Color.WHITE);
                } else if (t.isStatusTicket() == 3) {
                    jButton_B1.setBackground(Color.red);
                }
            } else if (i == 5) {
                if (t.isStatusTicket() == 1) {
                    jButton_B2.setBackground(Color.WHITE);
                } else if (t.isStatusTicket() == 3) {
                    jButton_B2.setBackground(Color.red);
                }
            } else if (i == 6) {
                if (t.isStatusTicket() == 1) {
                    jButton_B3.setBackground(Color.WHITE);
                } else if (t.isStatusTicket() == 3) {
                    jButton_B3.setBackground(Color.red);
                }
            } else if (i == 7) {
                if (t.isStatusTicket() == 1) {
                    jButton_C1.setBackground(Color.WHITE);
                } else if (t.isStatusTicket() == 3) {
                    jButton_C1.setBackground(Color.red);
                }
            } else if (i == 8) {
                if (t.isStatusTicket() == 1) {
                    jButton_C2.setBackground(Color.WHITE);
                } else if (t.isStatusTicket() == 3) {
                    jButton_C2.setBackground(Color.red);
                }
            } else if (i == 9) {
                if (t.isStatusTicket() == 1) {
                    jButton_C3.setBackground(Color.WHITE);
                } else if (t.isStatusTicket() == 3) {
                    jButton_C3.setBackground(Color.red);
                }
            }
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_A1 = new javax.swing.JButton();
        jButton_A2 = new javax.swing.JButton();
        jButton_A3 = new javax.swing.JButton();
        jButton_B1 = new javax.swing.JButton();
        jButton_B2 = new javax.swing.JButton();
        jButton_B3 = new javax.swing.JButton();
        jButton_C1 = new javax.swing.JButton();
        jButton_C2 = new javax.swing.JButton();
        jButton_C3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton_payMent = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jLabel_Sum = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Màn chiếu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton_A1.setText("A1");
        jButton_A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_A1ActionPerformed(evt);
            }
        });

        jButton_A2.setText("A2");
        jButton_A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_A2ActionPerformed(evt);
            }
        });

        jButton_A3.setText("A3");
        jButton_A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_A3ActionPerformed(evt);
            }
        });

        jButton_B1.setText("B1");
        jButton_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_B1ActionPerformed(evt);
            }
        });

        jButton_B2.setText("B2");
        jButton_B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_B2ActionPerformed(evt);
            }
        });

        jButton_B3.setText("B3");
        jButton_B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_B3ActionPerformed(evt);
            }
        });

        jButton_C1.setText("C1");
        jButton_C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_C1ActionPerformed(evt);
            }
        });

        jButton_C2.setText("C2");
        jButton_C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_C2ActionPerformed(evt);
            }
        });

        jButton_C3.setText("C3");
        jButton_C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_C3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_A1)
                    .addComponent(jButton_B1)
                    .addComponent(jButton_C1))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_C2)
                    .addComponent(jButton_B2)
                    .addComponent(jButton_A2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_A3)
                    .addComponent(jButton_B3)
                    .addComponent(jButton_C3))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_A2)
                    .addComponent(jButton_A1)
                    .addComponent(jButton_A3))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_B2)
                    .addComponent(jButton_B3)
                    .addComponent(jButton_B1))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_C2)
                    .addComponent(jButton_C1)
                    .addComponent(jButton_C3))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Tổng tiền:");

        jButton_payMent.setText("Thanh toán");
        jButton_payMent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_payMentActionPerformed(evt);
            }
        });

        jButton_Cancel.setText("Hủy");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jLabel_Sum.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton_payMent)
                        .addGap(42, 42, 42)
                        .addComponent(jButton_Cancel))
                    .addComponent(jLabel_Sum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Sum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_payMent)
                    .addComponent(jButton_Cancel))
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_icon_32.png"))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jLabel4.setText("Đã mua");

        jLabel5.setText("Đang chọn");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_payMentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_payMentActionPerformed
        if (s == 0) {
            MessageDialog.showMessageDialog(jPanel1, "Thông báo", "Cần chọn vé");
        } else {
            if (MessageDialog.showConfirmialog(jPanel1, "Hỏi", "Bạn có muốn đặt vé") == JOptionPane.NO_OPTION) {
                return;
            } else {
                TicketDao dao = new TicketDao();
                for (Ticket_model t : list) {
                    if (t.isStatusTicket() == 2) {
                        try {
                            dao.UpdateStatus(t.getIdTicket());
                        } catch (Exception ex) {
                            Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try {
                            dao.UpdatePhoneNumber(t.getIdTicket(), user.getPhoneNumber());
                        } catch (Exception ex) {
                            Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        t.setStatusTicket(3);
                    }
                }
                this.dispose();
                this.s = 0;
                this.jLabel_Sum.setText(s + "đ");
                this.setColor();
                this.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton_payMentActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        int count = 0;
        for (Ticket_model t : list) {
            if (t.isStatusTicket() == 2) {
                count++;
            }
        }
        if (count == 0)
            MessageDialog.showMessageDialog(jPanel1, "Thông báo", "Bạn chưa đặt vé");
        else {
            if (MessageDialog.showConfirmialog(jPanel1, "Hỏi", "Muốn hủy các vé đã đặt") == JOptionPane.NO_OPTION) {
                return;
            } else {
                for (Ticket_model t : list) {
                    if (t.isStatusTicket() == 2) {
                        t.setStatusTicket(1);
                    }
                }
                this.dispose();
                this.s = 0;
                this.jLabel_Sum.setText(s + "đ");
                this.setColor();
                this.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_C1ActionPerformed
        if (jButton_C1.getBackground() == Color.WHITE) {
            setYellow(jButton_C1);
            this.s += list.get(6).getPrice();
            this.list.get(6).setStatusTicket(2);
        } else if (jButton_C1.getBackground() == Color.YELLOW) {
            setWhite(jButton_C1);
            this.s -= list.get(6).getPrice();
            this.list.get(6).setStatusTicket(1);
        } else if (jButton_C1.getBackground() == Color.RED) {
            MessageDialog.showMessageDialog(jPanel1, "Ghế đã có người chọn", "Thông báo");
        }
        this.jLabel_Sum.setText((String) ss.format(this.s));
    }//GEN-LAST:event_jButton_C1ActionPerformed

    private void jButton_A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_A1ActionPerformed
        if (jButton_A1.getBackground() == Color.WHITE) {
            setYellow(jButton_A1);
            this.s += list.get(0).getPrice();
            this.list.get(0).setStatusTicket(2);
        } else if (jButton_A1.getBackground() == Color.YELLOW) {
            setWhite(jButton_A1);
            this.s -= list.get(0).getPrice();
            this.list.get(0).setStatusTicket(1);
        } else if (jButton_A1.getBackground() == Color.RED) {
            MessageDialog.showMessageDialog(jPanel1, "Thông báo", "Ghế đã có người chọn");
        }
        this.jLabel_Sum.setText((String) ss.format(this.s));
    }//GEN-LAST:event_jButton_A1ActionPerformed

    private void jButton_A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_A2ActionPerformed
        if (jButton_A2.getBackground() == Color.WHITE) {
            setYellow(jButton_A2);
            this.s += list.get(1).getPrice();
            this.list.get(1).setStatusTicket(2);
        } else if (jButton_A2.getBackground() == Color.YELLOW) {
            setWhite(jButton_A2);
            this.s -= list.get(1).getPrice();
            this.list.get(1).setStatusTicket(1);
        } else if (jButton_A2.getBackground() == Color.RED) {
            MessageDialog.showMessageDialog(jPanel1, "Thông báo", "Ghế đã có người chọn");
        }
        this.jLabel_Sum.setText((String) ss.format(this.s));
    }//GEN-LAST:event_jButton_A2ActionPerformed

    private void jButton_A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_A3ActionPerformed
        if (jButton_A3.getBackground() == Color.WHITE) {
            setYellow(jButton_A3);
            this.s += list.get(2).getPrice();
            this.list.get(2).setStatusTicket(2);
        } else if (jButton_A3.getBackground() == Color.YELLOW) {
            setWhite(jButton_A3);
            this.s -= list.get(2).getPrice();
            this.list.get(2).setStatusTicket(1);
        } else if (jButton_A3.getBackground() == Color.RED) {
            MessageDialog.showMessageDialog(jPanel1, "Thông báo", "Ghế đã có người chọn");
        }
        this.jLabel_Sum.setText((String) ss.format(this.s));
    }//GEN-LAST:event_jButton_A3ActionPerformed

    private void jButton_B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_B2ActionPerformed
        if (jButton_B2.getBackground() == Color.WHITE) {
            setYellow(jButton_B2);
            this.s += list.get(4).getPrice();
            this.list.get(4).setStatusTicket(2);
        } else if (jButton_B2.getBackground() == Color.YELLOW) {
            setWhite(jButton_B2);
            this.s -= list.get(4).getPrice();
            this.list.get(4).setStatusTicket(1);
        } else if (jButton_B2.getBackground() == Color.RED) {
            MessageDialog.showMessageDialog(jPanel1, "Thông báo", "Ghế đã có người chọn");
        }
        this.jLabel_Sum.setText((String) ss.format(this.s));
    }//GEN-LAST:event_jButton_B2ActionPerformed

    private void jButton_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_B1ActionPerformed
        if (jButton_B1.getBackground() == Color.WHITE) {
            setYellow(jButton_B1);
            this.s += list.get(3).getPrice();
            this.list.get(3).setStatusTicket(2);
        } else if (jButton_B1.getBackground() == Color.YELLOW) {
            setWhite(jButton_B1);
            this.s -= list.get(3).getPrice();
            this.list.get(3).setStatusTicket(1);
        } else if (jButton_A1.getBackground() == Color.RED) {
            MessageDialog.showMessageDialog(jPanel1, "Thông báo", "Ghế đã có người chọn");
        }
        this.jLabel_Sum.setText((String) ss.format(this.s));
    }//GEN-LAST:event_jButton_B1ActionPerformed

    private void jButton_B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_B3ActionPerformed
        if (jButton_B3.getBackground() == Color.WHITE) {
            setYellow(jButton_B3);
            this.s += list.get(5).getPrice();
            this.list.get(5).setStatusTicket(2);
        } else if (jButton_B3.getBackground() == Color.YELLOW) {
            setWhite(jButton_B3);
            this.s -= list.get(5).getPrice();
            this.list.get(5).setStatusTicket(1);
        } else if (jButton_B3.getBackground() == Color.RED) {
            MessageDialog.showMessageDialog(jPanel1, "Thông báo", "Ghế đã có người chọn");
        }
        this.jLabel_Sum.setText((String) ss.format(this.s));
    }//GEN-LAST:event_jButton_B3ActionPerformed

    private void jButton_C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_C2ActionPerformed
        if (jButton_C2.getBackground() == Color.WHITE) {
            setYellow(jButton_C2);
            this.s += list.get(7).getPrice();
            this.list.get(7).setStatusTicket(2);
        } else if (jButton_C2.getBackground() == Color.YELLOW) {
            setWhite(jButton_C2);
            this.s -= list.get(7).getPrice();
            this.list.get(7).setStatusTicket(1);
        } else if (jButton_C2.getBackground() == Color.RED) {
            MessageDialog.showMessageDialog(jPanel1, "Thông báo", "Ghế đã có người chọn");
        }
        this.jLabel_Sum.setText((String) ss.format(this.s));
    }//GEN-LAST:event_jButton_C2ActionPerformed

    private void jButton_C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_C3ActionPerformed
        if (jButton_C3.getBackground() == Color.WHITE) {
            setYellow(jButton_C3);
            this.s += list.get(8).getPrice();
            this.list.get(8).setStatusTicket(2);
        } else if (jButton_C3.getBackground() == Color.YELLOW) {
            setWhite(jButton_C3);
            this.s -= list.get(8).getPrice();
            this.list.get(8).setStatusTicket(1);
        } else if (jButton_C3.getBackground() == Color.RED) {
            MessageDialog.showMessageDialog(jPanel1, "Thông báo", "Ghế đã có người chọn");
        }
        this.jLabel_Sum.setText((String) ss.format(this.s));
    }//GEN-LAST:event_jButton_C3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ticket dialog = new Ticket(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_A1;
    private javax.swing.JButton jButton_A2;
    private javax.swing.JButton jButton_A3;
    private javax.swing.JButton jButton_B1;
    private javax.swing.JButton jButton_B2;
    private javax.swing.JButton jButton_B3;
    private javax.swing.JButton jButton_C1;
    private javax.swing.JButton jButton_C2;
    private javax.swing.JButton jButton_C3;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_payMent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Sum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
